name:                tsearch
version:             0.1.0
github:              "nufeen/tglib-haskell-bindings"
license:             WTFPL
author:              "Nufeen"
maintainer:          "darwin@email.su"
copyright:           "Nufeen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            tglib-haskell-bindings
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tsearch#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  tsearch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tsearch
